st.header("📦 PRODUCTS KPI")

st.subheader("Rep Products")
st.dataframe(rep["products_full"])
st.dataframe(rep["products_month"])
st.dataframe(rep["products_quarter"])
st.dataframe(rep["products_ytd"])

st.subheader("Manager Products")
st.dataframe(manager["products_full"])
st.dataframe(manager["products_month"])
st.dataframe(manager["products_quarter"])
st.dataframe(manager["products_ytd"])

st.subheader("Area Products")
st.dataframe(area["products_full"])
st.dataframe(area["products_month"])
st.dataframe(area["products_quarter"])
st.dataframe(area["products_ytd"])

st.subheader("Supervisor Products")
st.dataframe(supervisor["products_full"])
st.dataframe(supervisor["products_month"])
st.dataframe(supervisor["products_quarter"])
st.dataframe(supervisor["products_ytd"])

st.subheader("Evak Products")
st.dataframe(evak["products_full"])
st.dataframe(evak["products_month"])
st.dataframe(evak["products_quarter"])
st.dataframe(evak["products_ytd"])
